service: geoapp
frameworkVersion: "3"

package:
  patterns:
    - "!./**"
    - "Handlers/**"
    - "Classes/**"
    - "Utils/**"
    - "DataBase/**"

plugins:
  - serverless-offline

useDotenv: true

custom:
  globalTimeOut: 30

provider:
  name: aws
  runtime: python3.11

functions:
  UserApi:
    handler: Handlers/UserHandler.user
    timeout: ${self:custom.globalTimeOut}
    events:
      - http:
          path: /get_user
          method: get
      - http:
          path: /create_user
          method: post
      - http:
          path: /update_user
          method: put
      - http:
          path: /delete_user
          method: delete

  AddressApi:
    handler: Handlers/AddressHandler.address
    timeout: ${self:custom.globalTimeOut}
    events:
      - http:
          path: /get_address
          method: get
      - http:
          path: /create_address
          method: post
      - http:
          path: /update_address
          method: put
      - http:
          path: /delete_address
          method: delete

  DocumentTypeApi:
    handler: Handlers/DocumentTypeHandler.document_type
    timeout: ${self:custom.globalTimeOut}
    events:
      - http:
          path: /get_document_types
          method: get

  GenderApi:
    handler: Handlers/GenderHandler.gender
    timeout: ${self:custom.globalTimeOut}
    events:
      - http:
          path: /get_genders
          method: get

  CityApi:
    handler: Handlers/CityHandler.city
    timeout: ${self:custom.globalTimeOut}
    events:
      - http:
          path: /get_cities
          method: get

  StateApi:
    handler: Handlers/StateHandler.state
    timeout: ${self:custom.globalTimeOut}
    events:
      - http:
          path: /get_states
          method: get

  BankApi:
    handler: Handlers/BankHandler.bank
    timeout: ${self:custom.globalTimeOut}
    events:
      - http:
          path: /get_banks
          method: get

  PaymentCardApi:
    handler: Handlers/PaymentCardHandler.payment_card
    timeout: ${self:custom.globalTimeOut}
    events:
      - http:
          path: /get_user_cards
          method: get
      - http:
          path: /create_payment_card
          method: post
      - http:
          path: /update_payment_card
          method: put
      - http:
          path: /delete_payment_card
          method: delete

  EquipmentApi:
    handler: Handlers/ManagementHandler.management
    timeout: ${self:custom.globalTimeOut}
    events:
      - http:
          path: /get_managements
          method: get
      - http:
          path: /create_management
          method: post
      - http:
          path: /update_management
          method: put
      - http:
          path: /delete_management
          method: delete

  EquipmentMaintenanceStatusApi:
    handler: Handlers/MaintenanceStatusHandler.maintenance_status
    timeout: ${self:custom.globalTimeOut}
    events:
      - http:
          path: /equipment_maintenance_status
          method: get
      - http:
          path: /equipment_maintenance_status
          method: post

  AuthApi:
    handler: Handlers/AuthHandler.auth
    timeout: ${self:custom.globalTimeOut}
    events:
      - http:
          path: /auth
          method: post

  UserByTokenApi:
    handler: Handlers/UserHandler.user_data_by_token
    timeout: ${self:custom.globalTimeOut}
    events:
      - http:
          path: /get_user_data_by_token
          method: get

  LocationApi:
    handler: Handlers/LocationHandler.location
    timeout: ${self:custom.globalTimeOut}
    events:
      - http:
          path: /location
          method: get
